version: "3.8"

services:
  # webserver:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #     - ipfs
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: superpw
      MYSQL_DATABASE: superdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./ipfs-data:/data/ipfs
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

volumes:  
  mysql-data: